/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMyTrackRouteImport } from './routes/_authenticated/my-track'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDriverReportsRouteImport } from './routes/_authenticated/driver-reports'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiSmsTestRouteImport } from './routes/api/sms/test'
import { Route as ApiSmsBulkRouteImport } from './routes/api/sms/bulk'
import { Route as ApiSchedulesNotifyRouteImport } from './routes/api/schedules/notify'
import { Route as ApiPublicUssdRouteImport } from './routes/api/public/ussd'
import { Route as ApiDriversSetPasswordRouteImport } from './routes/api/drivers/set-password'
import { Route as ApiDriversInviteRouteImport } from './routes/api/drivers/invite'
import { Route as ApiDriverLocationRouteImport } from './routes/api/driver/location'
import { Route as ApiPublicIotDataRouteImport } from './routes/api/public/iot/data'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyTrackRoute = AuthenticatedMyTrackRouteImport.update({
  id: '/my-track',
  path: '/my-track',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverReportsRoute =
  AuthenticatedDriverReportsRouteImport.update({
    id: '/driver-reports',
    path: '/driver-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSmsTestRoute = ApiSmsTestRouteImport.update({
  id: '/api/sms/test',
  path: '/api/sms/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsBulkRoute = ApiSmsBulkRouteImport.update({
  id: '/api/sms/bulk',
  path: '/api/sms/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesNotifyRoute = ApiSchedulesNotifyRouteImport.update({
  id: '/api/schedules/notify',
  path: '/api/schedules/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUssdRoute = ApiPublicUssdRouteImport.update({
  id: '/api/public/ussd',
  path: '/api/public/ussd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriversSetPasswordRoute = ApiDriversSetPasswordRouteImport.update({
  id: '/api/drivers/set-password',
  path: '/api/drivers/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriversInviteRoute = ApiDriversInviteRouteImport.update({
  id: '/api/drivers/invite',
  path: '/api/drivers/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverLocationRoute = ApiDriverLocationRouteImport.update({
  id: '/api/driver/location',
  path: '/api/driver/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIotDataRoute = ApiPublicIotDataRouteImport.update({
  id: '/api/public/iot/data',
  path: '/api/public/iot/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/driver-reports': typeof AuthenticatedDriverReportsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/map': typeof AuthenticatedMapRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-track': typeof AuthenticatedMyTrackRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/driver/location': typeof ApiDriverLocationRoute
  '/api/drivers/invite': typeof ApiDriversInviteRoute
  '/api/drivers/set-password': typeof ApiDriversSetPasswordRoute
  '/api/public/ussd': typeof ApiPublicUssdRoute
  '/api/schedules/notify': typeof ApiSchedulesNotifyRoute
  '/api/sms/bulk': typeof ApiSmsBulkRoute
  '/api/sms/test': typeof ApiSmsTestRoute
  '/api/public/iot/data': typeof ApiPublicIotDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/driver-reports': typeof AuthenticatedDriverReportsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/map': typeof AuthenticatedMapRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-track': typeof AuthenticatedMyTrackRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/driver/location': typeof ApiDriverLocationRoute
  '/api/drivers/invite': typeof ApiDriversInviteRoute
  '/api/drivers/set-password': typeof ApiDriversSetPasswordRoute
  '/api/public/ussd': typeof ApiPublicUssdRoute
  '/api/schedules/notify': typeof ApiSchedulesNotifyRoute
  '/api/sms/bulk': typeof ApiSmsBulkRoute
  '/api/sms/test': typeof ApiSmsTestRoute
  '/api/public/iot/data': typeof ApiPublicIotDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/driver-reports': typeof AuthenticatedDriverReportsRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-track': typeof AuthenticatedMyTrackRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/driver/location': typeof ApiDriverLocationRoute
  '/api/drivers/invite': typeof ApiDriversInviteRoute
  '/api/drivers/set-password': typeof ApiDriversSetPasswordRoute
  '/api/public/ussd': typeof ApiPublicUssdRoute
  '/api/schedules/notify': typeof ApiSchedulesNotifyRoute
  '/api/sms/bulk': typeof ApiSmsBulkRoute
  '/api/sms/test': typeof ApiSmsTestRoute
  '/api/public/iot/data': typeof ApiPublicIotDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/devices'
    | '/driver-reports'
    | '/drivers'
    | '/map'
    | '/messages'
    | '/my-track'
    | '/reports'
    | '/routes'
    | '/schedules'
    | '/vehicles'
    | '/api/driver/location'
    | '/api/drivers/invite'
    | '/api/drivers/set-password'
    | '/api/public/ussd'
    | '/api/schedules/notify'
    | '/api/sms/bulk'
    | '/api/sms/test'
    | '/api/public/iot/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/devices'
    | '/driver-reports'
    | '/drivers'
    | '/map'
    | '/messages'
    | '/my-track'
    | '/reports'
    | '/routes'
    | '/schedules'
    | '/vehicles'
    | '/api/driver/location'
    | '/api/drivers/invite'
    | '/api/drivers/set-password'
    | '/api/public/ussd'
    | '/api/schedules/notify'
    | '/api/sms/bulk'
    | '/api/sms/test'
    | '/api/public/iot/data'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/driver-reports'
    | '/_authenticated/drivers'
    | '/_authenticated/map'
    | '/_authenticated/messages'
    | '/_authenticated/my-track'
    | '/_authenticated/reports'
    | '/_authenticated/routes'
    | '/_authenticated/schedules'
    | '/_authenticated/vehicles'
    | '/api/driver/location'
    | '/api/drivers/invite'
    | '/api/drivers/set-password'
    | '/api/public/ussd'
    | '/api/schedules/notify'
    | '/api/sms/bulk'
    | '/api/sms/test'
    | '/api/public/iot/data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiDriverLocationRoute: typeof ApiDriverLocationRoute
  ApiDriversInviteRoute: typeof ApiDriversInviteRoute
  ApiDriversSetPasswordRoute: typeof ApiDriversSetPasswordRoute
  ApiPublicUssdRoute: typeof ApiPublicUssdRoute
  ApiSchedulesNotifyRoute: typeof ApiSchedulesNotifyRoute
  ApiSmsBulkRoute: typeof ApiSmsBulkRoute
  ApiSmsTestRoute: typeof ApiSmsTestRoute
  ApiPublicIotDataRoute: typeof ApiPublicIotDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-track': {
      id: '/_authenticated/my-track'
      path: '/my-track'
      fullPath: '/my-track'
      preLoaderRoute: typeof AuthenticatedMyTrackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver-reports': {
      id: '/_authenticated/driver-reports'
      path: '/driver-reports'
      fullPath: '/driver-reports'
      preLoaderRoute: typeof AuthenticatedDriverReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/sms/test': {
      id: '/api/sms/test'
      path: '/api/sms/test'
      fullPath: '/api/sms/test'
      preLoaderRoute: typeof ApiSmsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/bulk': {
      id: '/api/sms/bulk'
      path: '/api/sms/bulk'
      fullPath: '/api/sms/bulk'
      preLoaderRoute: typeof ApiSmsBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules/notify': {
      id: '/api/schedules/notify'
      path: '/api/schedules/notify'
      fullPath: '/api/schedules/notify'
      preLoaderRoute: typeof ApiSchedulesNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ussd': {
      id: '/api/public/ussd'
      path: '/api/public/ussd'
      fullPath: '/api/public/ussd'
      preLoaderRoute: typeof ApiPublicUssdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drivers/set-password': {
      id: '/api/drivers/set-password'
      path: '/api/drivers/set-password'
      fullPath: '/api/drivers/set-password'
      preLoaderRoute: typeof ApiDriversSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drivers/invite': {
      id: '/api/drivers/invite'
      path: '/api/drivers/invite'
      fullPath: '/api/drivers/invite'
      preLoaderRoute: typeof ApiDriversInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/location': {
      id: '/api/driver/location'
      path: '/api/driver/location'
      fullPath: '/api/driver/location'
      preLoaderRoute: typeof ApiDriverLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iot/data': {
      id: '/api/public/iot/data'
      path: '/api/public/iot/data'
      fullPath: '/api/public/iot/data'
      preLoaderRoute: typeof ApiPublicIotDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedDriverReportsRoute: typeof AuthenticatedDriverReportsRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyTrackRoute: typeof AuthenticatedMyTrackRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedDriverReportsRoute: AuthenticatedDriverReportsRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyTrackRoute: AuthenticatedMyTrackRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiDriverLocationRoute: ApiDriverLocationRoute,
  ApiDriversInviteRoute: ApiDriversInviteRoute,
  ApiDriversSetPasswordRoute: ApiDriversSetPasswordRoute,
  ApiPublicUssdRoute: ApiPublicUssdRoute,
  ApiSchedulesNotifyRoute: ApiSchedulesNotifyRoute,
  ApiSmsBulkRoute: ApiSmsBulkRoute,
  ApiSmsTestRoute: ApiSmsTestRoute,
  ApiPublicIotDataRoute: ApiPublicIotDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
